project_id = "gdbodrzxdbtskyzmqmuu"

[functions.create-checkout-session]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.prerender]
verify_jwt = false